import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/assets/images/fiingLogo.svg";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fiing | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar logo={Logo}/>
          {children}
      </body>
    </html>
  );
}
